/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const MobileNumber = IDL.Text;
export const VerificationRequest = IDL.Record({
  'verificationCode' : IDL.Text,
  'mobileNumber' : MobileNumber,
});
export const MobileVerificationStatus = IDL.Record({ 'verified' : IDL.Bool });
export const ServiceCategoryId = IDL.Nat;
export const Time = IDL.Int;
export const BookingRequest = IDL.Record({
  'serviceCategory' : ServiceCategoryId,
  'address' : IDL.Text,
  'preferredTime' : Time,
  'timeSlot' : IDL.Text,
});
export const BookingResponse = IDL.Record({ 'message' : IDL.Text });
export const IVRBookingRequest = IDL.Record({
  'serviceCategory' : ServiceCategoryId,
  'address' : IDL.Text,
  'mobile' : MobileNumber,
  'timeSlot' : IDL.Text,
});
export const SubscriptionPlanId = IDL.Nat;
export const SupportTicketId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'address' : IDL.Text,
  'preferredTime' : Time,
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'category' : ServiceCategoryId,
  'customerId' : IDL.Principal,
  'timeSlot' : IDL.Text,
});
export const FeedbackId = IDL.Nat;
export const Feedback = IDL.Record({
  'id' : FeedbackId,
  'bookingId' : BookingId,
  'rating' : IDL.Nat,
  'comments' : IDL.Text,
});
export const PaymentId = IDL.Nat;
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : IDL.Text,
  'method' : IDL.Text,
  'bookingId' : BookingId,
  'amount' : IDL.Nat,
});
export const SupportTicket = IDL.Record({
  'id' : SupportTicketId,
  'status' : IDL.Text,
  'message' : IDL.Text,
  'customerId' : IDL.Principal,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
  'zone' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'isVerified' : IDL.Bool,
});
export const IVRTaskId = IDL.Nat;
export const IVRTask = IDL.Record({
  'id' : IVRTaskId,
  'status' : IDL.Text,
  'bookingId' : BookingId,
  'taskType' : IDL.Text,
});
export const SubscriptionPlan = IDL.Record({
  'id' : SubscriptionPlanId,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const ServiceCategory = IDL.Record({
  'id' : ServiceCategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignStaffToBooking' : IDL.Func([BookingId, IDL.Principal], [], []),
  'completeVerification' : IDL.Func(
      [VerificationRequest],
      [MobileVerificationStatus],
      [],
    ),
  'createBooking' : IDL.Func([BookingRequest], [BookingResponse], []),
  'createIvrVerification' : IDL.Func([IVRBookingRequest], [], []),
  'createServiceCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ServiceCategoryId],
      [],
    ),
  'createSubscriptionPlan' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [SubscriptionPlanId],
      [],
    ),
  'createSupportTicket' : IDL.Func([IDL.Text], [SupportTicketId], []),
  'demoBookingsWithLocations' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getAvailableTimeSlots' : IDL.Func(
      [ServiceCategoryId],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIVRTasks' : IDL.Func([], [IDL.Vec(IVRTask)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getSubscriptionPlans' : IDL.Func([], [IDL.Vec(SubscriptionPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([BookingId, IDL.Text, IDL.Nat], [PaymentId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  'startVerification' : IDL.Func([IDL.Text], [MobileVerificationStatus], []),
  'submitFeedback' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
  'updateIVRTaskStatus' : IDL.Func([IVRTaskId, IDL.Text], [], []),
  'updatePaymentStatus' : IDL.Func([PaymentId, IDL.Text], [], []),
  'viewServiceCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const MobileNumber = IDL.Text;
  const VerificationRequest = IDL.Record({
    'verificationCode' : IDL.Text,
    'mobileNumber' : MobileNumber,
  });
  const MobileVerificationStatus = IDL.Record({ 'verified' : IDL.Bool });
  const ServiceCategoryId = IDL.Nat;
  const Time = IDL.Int;
  const BookingRequest = IDL.Record({
    'serviceCategory' : ServiceCategoryId,
    'address' : IDL.Text,
    'preferredTime' : Time,
    'timeSlot' : IDL.Text,
  });
  const BookingResponse = IDL.Record({ 'message' : IDL.Text });
  const IVRBookingRequest = IDL.Record({
    'serviceCategory' : ServiceCategoryId,
    'address' : IDL.Text,
    'mobile' : MobileNumber,
    'timeSlot' : IDL.Text,
  });
  const SubscriptionPlanId = IDL.Nat;
  const SupportTicketId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'address' : IDL.Text,
    'preferredTime' : Time,
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'category' : ServiceCategoryId,
    'customerId' : IDL.Principal,
    'timeSlot' : IDL.Text,
  });
  const FeedbackId = IDL.Nat;
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'bookingId' : BookingId,
    'rating' : IDL.Nat,
    'comments' : IDL.Text,
  });
  const PaymentId = IDL.Nat;
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : IDL.Text,
    'method' : IDL.Text,
    'bookingId' : BookingId,
    'amount' : IDL.Nat,
  });
  const SupportTicket = IDL.Record({
    'id' : SupportTicketId,
    'status' : IDL.Text,
    'message' : IDL.Text,
    'customerId' : IDL.Principal,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'name' : IDL.Text,
    'zone' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'isVerified' : IDL.Bool,
  });
  const IVRTaskId = IDL.Nat;
  const IVRTask = IDL.Record({
    'id' : IVRTaskId,
    'status' : IDL.Text,
    'bookingId' : BookingId,
    'taskType' : IDL.Text,
  });
  const SubscriptionPlan = IDL.Record({
    'id' : SubscriptionPlanId,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ServiceCategory = IDL.Record({
    'id' : ServiceCategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignStaffToBooking' : IDL.Func([BookingId, IDL.Principal], [], []),
    'completeVerification' : IDL.Func(
        [VerificationRequest],
        [MobileVerificationStatus],
        [],
      ),
    'createBooking' : IDL.Func([BookingRequest], [BookingResponse], []),
    'createIvrVerification' : IDL.Func([IVRBookingRequest], [], []),
    'createServiceCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ServiceCategoryId],
        [],
      ),
    'createSubscriptionPlan' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [SubscriptionPlanId],
        [],
      ),
    'createSupportTicket' : IDL.Func([IDL.Text], [SupportTicketId], []),
    'demoBookingsWithLocations' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getAvailableTimeSlots' : IDL.Func(
        [ServiceCategoryId],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIVRTasks' : IDL.Func([], [IDL.Vec(IVRTask)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([BookingId, IDL.Text, IDL.Nat], [PaymentId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
    'startVerification' : IDL.Func([IDL.Text], [MobileVerificationStatus], []),
    'submitFeedback' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
    'updateIVRTaskStatus' : IDL.Func([IVRTaskId, IDL.Text], [], []),
    'updatePaymentStatus' : IDL.Func([PaymentId, IDL.Text], [], []),
    'viewServiceCategories' : IDL.Func(
        [],
        [IDL.Vec(ServiceCategory)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };