/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'staff' : null };
export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'address' : string,
  'preferredTime' : Time,
  'assignedStaff' : [] | [Principal],
  'category' : ServiceCategoryId,
  'customerId' : Principal,
  'timeSlot' : string,
}
export type BookingId = bigint;
export interface BookingRequest {
  'serviceCategory' : ServiceCategoryId,
  'address' : string,
  'preferredTime' : Time,
  'timeSlot' : string,
}
export interface BookingResponse { 'message' : string }
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface Feedback {
  'id' : FeedbackId,
  'bookingId' : BookingId,
  'rating' : bigint,
  'comments' : string,
}
export type FeedbackId = bigint;
export interface IVRBookingRequest {
  'serviceCategory' : ServiceCategoryId,
  'address' : string,
  'mobile' : MobileNumber,
  'timeSlot' : string,
}
export interface IVRTask {
  'id' : IVRTaskId,
  'status' : string,
  'bookingId' : BookingId,
  'taskType' : string,
}
export type IVRTaskId = bigint;
export type MobileNumber = string;
export interface MobileVerificationStatus { 'verified' : boolean }
export interface Payment {
  'id' : PaymentId,
  'status' : string,
  'method' : string,
  'bookingId' : BookingId,
  'amount' : bigint,
}
export type PaymentId = bigint;
export interface ServiceCategory {
  'id' : ServiceCategoryId,
  'name' : string,
  'description' : string,
}
export type ServiceCategoryId = bigint;
export interface SubscriptionPlan {
  'id' : SubscriptionPlanId,
  'name' : string,
  'price' : bigint,
}
export type SubscriptionPlanId = bigint;
export interface SupportTicket {
  'id' : SupportTicketId,
  'status' : string,
  'message' : string,
  'customerId' : Principal,
}
export type SupportTicketId = bigint;
export type Time = bigint;
export interface UserProfile {
  'appRole' : AppRole,
  'name' : string,
  'zone' : string,
  'mobileNumber' : string,
  'isVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationRequest {
  'verificationCode' : string,
  'mobileNumber' : MobileNumber,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignStaffToBooking' : ActorMethod<[BookingId, Principal], undefined>,
  'completeVerification' : ActorMethod<
    [VerificationRequest],
    MobileVerificationStatus
  >,
  'createBooking' : ActorMethod<[BookingRequest], BookingResponse>,
  'createIvrVerification' : ActorMethod<[IVRBookingRequest], undefined>,
  'createServiceCategory' : ActorMethod<[string, string], ServiceCategoryId>,
  'createSubscriptionPlan' : ActorMethod<[string, bigint], SubscriptionPlanId>,
  'createSupportTicket' : ActorMethod<[string], SupportTicketId>,
  'demoBookingsWithLocations' : ActorMethod<[], Array<Booking>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllSupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getAvailableTimeSlots' : ActorMethod<[ServiceCategoryId], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIVRTasks' : ActorMethod<[], Array<IVRTask>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMySupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[BookingId, string, bigint], PaymentId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserAppRole' : ActorMethod<[Principal, AppRole], undefined>,
  'startVerification' : ActorMethod<[string], MobileVerificationStatus>,
  'submitFeedback' : ActorMethod<[BookingId, bigint, string], undefined>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], undefined>,
  'updateIVRTaskStatus' : ActorMethod<[IVRTaskId, string], undefined>,
  'updatePaymentStatus' : ActorMethod<[PaymentId, string], undefined>,
  'viewServiceCategories' : ActorMethod<[], Array<ServiceCategory>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];